version: '3.4'

services:
  eventstore_db:
    image: lync/eventstore:with-cer-local #eventstore/eventstore
    command: --ext-ip=0.0.0.0 --int-ip=0.0.0.0 --db /data/db --config=/data/config.yml --enable-external-tcp
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_INT_TCP_PORT=1112
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_INT_HTTP_PORT=2112
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_EXT_SECURE_TCP_PORT=1115
      - EVENTSTORE_CERTIFICATE_FILE=eventstore.p12      
    ports:
      - 1113:1113
      - 1115:1115
      - 2113:2113
    restart: always
    volumes:
      - 'eventstore_db_data:/data/db'

volumes:
  eventstore_db_data:
    driver: local
